CREATE DATABASE TEST;

CREATE TABLE `USERS` (
	`id` int(10) NOT NULL AUTO_INCREMENT,
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;